# Generated by Django 3.0.9 on 2020-08-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200804_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreView',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movie.Actor')),
            ],
            bases=('movie.actor',),
        ),
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
