# Generated by Django 3.0.9 on 2020-08-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200805_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
    ]
