# Generated by Django 3.0.9 on 2020-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_actor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=160),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
