# Generated by Django 3.0.9 on 2020-08-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200805_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
    ]
