# Generated by Django 3.0.9 on 2020-08-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_actor_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
    ]
