# Generated by Django 3.0.9 on 2020-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_actor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=150, verbose_name='Имя'), max_length=160),
        ),
    ]
