# Generated by Django 3.0.9 on 2020-08-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20200805_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreView',
        ),
    ]
